/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Aluno
 */
public class JfrTela extends javax.swing.JFrame {

    /**
     * Creates new form JfrTela
     */
    public JfrTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbAc = new javax.swing.JButton();
        jbSinal = new javax.swing.JButton();
        jbPorcentagem = new javax.swing.JButton();
        jbDividir = new javax.swing.JButton();
        jbSete = new javax.swing.JButton();
        jbOito = new javax.swing.JButton();
        jbNove = new javax.swing.JButton();
        jbMultiplica = new javax.swing.JButton();
        jbQuatro = new javax.swing.JButton();
        jbCinco = new javax.swing.JButton();
        jbSeis = new javax.swing.JButton();
        jbMenos = new javax.swing.JButton();
        jbUm = new javax.swing.JButton();
        jbDois = new javax.swing.JButton();
        jbTres = new javax.swing.JButton();
        jbMais = new javax.swing.JButton();
        jbZero = new javax.swing.JButton();
        jbVirgula = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jValor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValor.setText("0,00");
        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        jbAc.setText("AC");
        jbAc.setAlignmentX(4.0F);
        jbAc.setAlignmentY(5.0F);
        jbAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcActionPerformed(evt);
            }
        });
        jPanel1.add(jbAc);

        jbSinal.setText("+/-");
        jPanel1.add(jbSinal);

        jbPorcentagem.setText("%");
        jPanel1.add(jbPorcentagem);

        jbDividir.setText("/");
        jPanel1.add(jbDividir);

        jbSete.setText("7");
        jbSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeteActionPerformed(evt);
            }
        });
        jPanel1.add(jbSete);

        jbOito.setText("8");
        jPanel1.add(jbOito);

        jbNove.setText("9");
        jPanel1.add(jbNove);

        jbMultiplica.setText("*");
        jPanel1.add(jbMultiplica);

        jbQuatro.setText("4");
        jPanel1.add(jbQuatro);

        jbCinco.setText("5");
        jPanel1.add(jbCinco);

        jbSeis.setText("6");
        jPanel1.add(jbSeis);

        jbMenos.setText("-");
        jPanel1.add(jbMenos);

        jbUm.setText("1");
        jPanel1.add(jbUm);

        jbDois.setText("2");
        jPanel1.add(jbDois);

        jbTres.setText("3");
        jPanel1.add(jbTres);

        jbMais.setText("+");
        jPanel1.add(jbMais);

        jbZero.setText("0");
        jPanel1.add(jbZero);

        jbVirgula.setText(",");
        jPanel1.add(jbVirgula);

        jbFechar.setText("Fechar");
        jPanel1.add(jbFechar);

        jbIgual.setText("=");
        jPanel1.add(jbIgual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jValor))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jValorActionPerformed

    private void jbAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAcActionPerformed

    private void jbSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSeteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jValor;
    private javax.swing.JButton jbAc;
    private javax.swing.JButton jbCinco;
    private javax.swing.JButton jbDividir;
    private javax.swing.JButton jbDois;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbIgual;
    private javax.swing.JButton jbMais;
    private javax.swing.JButton jbMenos;
    private javax.swing.JButton jbMultiplica;
    private javax.swing.JButton jbNove;
    private javax.swing.JButton jbOito;
    private javax.swing.JButton jbPorcentagem;
    private javax.swing.JButton jbQuatro;
    private javax.swing.JButton jbSeis;
    private javax.swing.JButton jbSete;
    private javax.swing.JButton jbSinal;
    private javax.swing.JButton jbTres;
    private javax.swing.JButton jbUm;
    private javax.swing.JButton jbVirgula;
    private javax.swing.JButton jbZero;
    // End of variables declaration//GEN-END:variables
}
